name: Deploy via FTP to ISPmanager

# Триггер: пуши только в ветку main
on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy to ISPmanager (FTP)
    runs-on: ubuntu-latest

    steps:
      # 1) Получаем код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Загружаем файлы по FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # Адрес вашего FTP-сервера
          server: ${{ secrets.FTP_HOST }}
          # Логин и пароль, которые вы добавили в Secrets
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Локальная папка с собранным сайтом (замените, если у вас не ./public)
          local-dir: ./www/
          # Путь на сервере, куда заливаются файлы (замените на ваш)
          server-dir: /
          # Доп. опции (можно убрать --insecure, если SSL-сертификат на сервере валидный)
          git-ftp-args: --insecure
